CREATE DATABASE dev62;

CREATE TABLE `dev62`.`users` (`u_id` INT(10) NOT NULL AUTO_INCREMENT , `u_name` VARCHAR(255) NOT NULL , `u_email` VARCHAR(255) NOT NULL , `u_pass` VARCHAR(255) NOT NULL , PRIMARY KEY (`u_id`)) ENGINE = InnoDB;